### ISSUE TITLE
Export.yaml doesn't produce .csv files.

### ISSUE THREAD

**Issue by jerajx** [timelyart/Kairos#70]
**Describe the bug**
export_mj.yaml doesn't produce .csv files, only creates timestamped folder in the export folder. In the log file it seems like nothing's wrong. I'm attaching config file, yaml file and log file.

**Expected behavior**
exported data in csv files for tickers in a watchlist

**Desktop (please complete the following information):**
I'm using windows 11, 
chrome + chromedriver 104.0.

[export_mj.yaml.zip](https://github.com/timelyart/Kairos/files/9382808/export_mj.yaml.zip)

**Comment by timelyart** [comment]
Fixed in [release v2.77](https://github.com/timelyart/Kairos/releases/tag/v2.77).

**Comment by jerajx** [comment]
Hi, 
there is no change in the export of chart data. CSV files are still not generated, only empty folder. No error in log file though. 
Best regards,
-Marko

**Comment by timelyart** [comment]
Please try to set either: 
* `download_file = 0.5` in your [kairos.cfg](https://github.com/timelyart/Kairos/blob/master/_kairos.cfg) under `[delays]` for a general setting
* `delays: {DELAY_DOWNLOAD_FILE: 0.5}` in your .yaml files for specific runs

This will let Kairos wait for 0.5 seconds after each download starts to allow the browser to finish downloading the file before the next ticker or the end of the run.

Let me know if this has worked out for you.

**Comment by jerajx** [comment]
hi, 
It didn't worked out. I already changed this parameter before even to 5 and still didn't work. 

I also tried on another computer with windows 10 and didn't work as well.
BR

**Comment by jerajx** [comment]
I tried also chrome + chromedriver 103.0 and 99.0. and did't work none of them. (win 10)

**Comment by timelyart** [comment]
I don't know what to tell you. I tested it with Ubuntu 18.04, 22.04 and Windows 10 with Chrome version 104.x (latest stable). 

Did you run with python3 and with an elevated prompt?

**Comment by jerajx** [comment]
Yes python 3.10 and elevated command prompt. Installed from scratch step by
step as instructed.

V sob., 27. avg. 2022 18:44 je oseba timelyart ***@***.***>
napisala:

**Comment by timelyart** [comment]
Maybe one of the dependencies screwed up. 
Did you have any errors during installation? Can you check for me which version of Selenium you have installed?
Are you using a virtual environment?

Maybe you can get some pointers from setting the logging 'level' to debugging (10). You'll find it under `[logging]->level` in your [kairos.cfg](https://github.com/timelyart/Kairos/blob/master/_kairos.cfg).

Reopened the issue whilst the investigation is ongoing.

**Comment by jerajx** [comment]
Hi,

selenium version is 3.141.0, I'm not using any virtual environment, plain
win10 or win11.
I'm attaching the logs.

Thanks,
Best regards, Marko

V V ned., 28. avg. 2022 ob 13:19 je oseba timelyart <
***@***.***> napisala:

**Comment by timelyart** [comment]
I don't see anything wrong with either your `kairos.cfg` or your `.yaml`. 

However, your log file does not include debug information. Please, change your 'logging level' to `10` in your `kairos.cfg` per the earlier instruction. Please, run it again with the latest Chrome version (browser and driver) and send me the log file.

**Comment by jerajx** [comment]
Hi,

I'm sending you the log and cfg files.

Chrome + chromedriver 105.0.

Best regards,
Marko



V V pet., 30. sep. 2022 ob 16:33 je oseba timelyart <
***@***.***> napisala:

**Comment by timelyart** [comment]
I did not receive the files. Are you sure you send them?

**Comment by jerajx** [comment]
Hi,
I'm sending you the logs and config files in a zip file. There are produced
on Windows 11, Chrome 105.0, python  3.10.6

Please confirm if you received the attachment this time.

Best regards,
Marko




V V pon., 3. okt. 2022 ob 08:35 je oseba Marko Jeraj <
***@***.***> napisala:

**Comment by timelyart** [comment]
Negative. I am not receiving any files from you. 
Please, try to login into Github and comment directly with your files instead of answering via email.

**Comment by jerajx** [comment]
[exportLog03-10-2022.zip](https://github.com/timelyart/Kairos/files/9810482/exportLog03-10-2022.zip)

I attached the zip file directly on github now.
Best regards,
Marko

**Comment by timelyart** [comment]
### Setup
Alright... I used your files and made the following changes:

* **kairos.cfg**: `username`, `password` and `path` (webdriver path)
* **export_mj.yaml**: `url` and `watchlists`

I made of copy of your chart and used that for `url`.

### Results
Using the setup above I was **not** able to reproduce the problem.

I noticed you have set `accept_cookies = false` in your **kairos.cfg**. So, I cleared my cache and tested again to make sure it wasn't cookies or the cookie banner.
Unfortunately, I am still not able to reproduce the issue. 

### Conclusion
Unable to reproduce the issue.

Which account level do you have?
I assume you have tested this, but can you manually export the data for each ticker you have in your watchlist?

**Comment by jerajx** [comment]
Hi,
That's strange, maybe there is something with python installation then or a
security issue. I did the installation step by step by your instructions,
on two separate computers, one running win10 and one running win11. I also
diseabled the antivirus. As i see chrome sometimes prevents dowloading
files for security reasons.

My premium subscription just expired a week ago, while it was active i
could and i actually did download some chart data, the same day i tried to
dowload them with kairos.

I intend to resubscribe shortly, probably on black friday to get more
reasonable price. Then i will be able to make further testing.

Best regards,
Marko

V sob., 22. okt. 2022 18:09 je oseba timelyart ***@***.***>
napisala:

**Comment by timelyart** [comment]
I doubt it is the python installation and Kairos is meant to be used with Chrome's default settings. 

I also noticed you don't use a separate user data directory for Chrome. If you use Kairos in this way, it means that if you happen to work/browse in Chrome that this will interfere with Kairos. However, your log file does not hint that you used Chrome at the same as Kairos.

**Comment by timelyart** [comment]
At this point, all we can hope for is that when you get your subscription back this issue has been magically resolved.

**Comment by jerajx** [comment]
I'm running python 3.10.6.



V V sob., 22. okt. 2022 ob 19:25 je oseba timelyart <
***@***.***> napisala:

**Comment by jerajx** [comment]
This issue solved by itself (almost). I created a brand new tradingview table (new url) and this one worked fine. Before that I tried several saved tables (URLs), which were all created a while ago, and now a brand new table finally worked. Who would thought of that? Please close this issue. Thanks!

**Comment by timelyart** [comment]
How exotic! 

Well, I am happy to hear that it finally got resolved and thank you for sharing the suspected problem.
